import subprocess
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_nfo(video_path, output_path, template='full'):
    """
    Generate NFO file using mediainfo with custom formatting
    
    Args:
        video_path: Path to video file
        output_path: Path where NFO file will be saved
        template: Output format (full, basic, or custom)
    
    Returns:
        dict with status and message
    """
    try:
        video_file = Path(video_path)
        release_name = video_file.stem
        
        # Get MediaInfo output
        cmd = ['mediainfo', '--Full', video_path]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        mediainfo_content = result.stdout
        
        # Create custom formatted NFO
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        nfo_content = f"""============================================================
Release Name : {release_name}
Added On     : {current_time}
============================================================

{mediainfo_content}

============================================================
Generated by Torrent & NFO Creator
============================================================
"""
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(nfo_content)
        
        logger.info(f"NFO created successfully: {output_path}")
        return {
            'success': True,
            'path': output_path,
            'message': 'NFO file created successfully'
        }
        
    except subprocess.CalledProcessError as e:
        logger.error(f"Error creating NFO: {e.stderr}")
        return {
            'success': False,
            'error': e.stderr
        }
    except Exception as e:
        logger.error(f"Unexpected error creating NFO: {e}")
        return {
            'success': False,
            'error': str(e)
        }
