import subprocess
import logging
from datetime import datetime
from pathlib import Path
import re

logger = logging.getLogger(__name__)


def generate_nfo(video_path, output_path, template='full', extra_info=None):
    """
    Generate NFO file using mediainfo with custom formatting
    
    Args:
        video_path: Path to video file
        output_path: Path where NFO file will be saved
        template: Output format (full, basic, or custom)
        extra_info: Optional dict with additional metadata:
            - release_name: Release name (sourceTitle from Radarr)
            - original_filename: Original filename after Radarr rename
            - radarr_movie: Full Radarr movie metadata dict
    
    Returns:
        dict with status and message
    """
    try:
        video_file = Path(video_path)
        
        # Determine release name
        if extra_info and extra_info.get('release_name'):
            release_name = extra_info['release_name']
        else:
            release_name = video_file.stem
        
        # Get MediaInfo output
        cmd = ['mediainfo', '--Full', video_path]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        mediainfo_content = result.stdout
        
        # Replace "Complete name" with release name + extension
        video_extension = video_file.suffix
        release_filename = f"{release_name}{video_extension}"
        
        # Replace the Complete name line in mediainfo
        mediainfo_content = re.sub(
            r'Complete name\s+: .+',
            f'Complete name                            : {release_filename}',
            mediainfo_content
        )
        
        # Create custom formatted NFO
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Build header with release info
        header = f"""================================================================================
                           RELEASE INFORMATION
================================================================================

Release Name    : {release_name}
"""
        
        # Add Radarr metadata if available
        if extra_info and extra_info.get('radarr_movie'):
            movie = extra_info['radarr_movie']
            header += f"\n"
            header += f"Title           : {movie.get('title', 'N/A')}\n"
            header += f"Year            : {movie.get('year', 'N/A')}\n"
            
            if movie.get('tmdbId'):
                header += f"TMDb ID         : {movie.get('tmdbId')}\n"
            
            if movie.get('imdbId'):
                header += f"IMDb ID         : {movie.get('imdbId')}\n"
            
            # Quality info
            movie_file = movie.get('movieFile', {})
            if movie_file:
                quality = movie_file.get('quality', {}).get('quality', {})
                if quality.get('name'):
                    header += f"Quality         : {quality.get('name')}\n"
                
                # Edition
                edition = movie_file.get('edition', '').strip()
                if edition:
                    header += f"Edition         : {edition}\n"
        
        header += f"\nAdded On        : {current_time}\n"
        
        # Assemble final NFO
        nfo_content = f"""{header}
================================================================================
                           TECHNICAL INFORMATION
================================================================================

{mediainfo_content}

================================================================================
                        Generated by Torrent-nfo-creator
================================================================================
"""
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(nfo_content)
        
        logger.info(f"NFO created successfully: {output_path}")
        return {
            'success': True,
            'path': output_path,
            'message': 'NFO file created successfully'
        }
        
    except subprocess.CalledProcessError as e:
        logger.error(f"Error creating NFO: {e.stderr}")
        return {
            'success': False,
            'error': e.stderr
        }
    except Exception as e:
        logger.error(f"Unexpected error creating NFO: {e}")
        return {
            'success': False,
            'error': str(e)
        }
